### ISSUE TITLE
babylonjs support for openctm

### ISSUE THREAD

**Issue by v3ss0n** [jcmellado/js-openctm#6]
can we get a port for babylonjs?

**Comment by jcmellado** [comment]
You could write a Babylon loader:

https://github.com/BabylonJS/Babylon.js/tree/master/loaders

three.js use the same approach:

https://github.com/mrdoob/three.js/tree/master/examples/js/loaders/ctm

**Comment by v3ss0n** [comment]
thanks

**Comment by stefangordon** [comment]
I was actually thinking that we should iterate on the binary .babylon exporter and optimize it based on OpenCTM.  It would be a huge size reduction over the existing implementation, and with some sort of versioning support we could maintain backwards compatibility.

I actually have some c# openctm code already, and threejs has a sample JS loader, so it shouldn't be too much work.  I hope to look at it soon...
